---
title: "IM- Rational Exponents"
author: "Rheamae Cerdenola"
format: html
editor: visual
---

## Lesson 3. Rational Exponents

If $x^{n}=y$, then$x$ is called the *nth root of y*. In symbols, we have $x =\sqrt[n]{y}$ . This is called a **radical expression** where *y* is the *radicand* while *n* is the *index*. For instance, since $2^3 = 8$, we say that the cube root of 8 is 2 or $\sqrt[3]{8} = 2$. Similarly, since $3^4 = 81$, we say that the fourth root of 81 is 3. Note that -3 is also a fourth root of 81 since $(-3)^4 = 81$. Thus, 81 has two fourth roots. The positive root 3 is called the principal fourth root of 81. Note that there is only one cube root of 8 and -8 which are 2 and -2, respectively. We say that the principal cube root of 8 is 2 while the principal cube root of -8 is -2.

In general, if the index is even, the principal root of a radicand is positive. If the radicand is negative, the number has no root. On the other hand, if the index is odd, the principal root of a positive number is positive while the principal root of a negative number is negative.

> Example:
>
> 1.  The square root of 81 is 9.
>
> 2.  -16 has no principal square root.
>
> 3.  The principal fifth root of 32 is 2.
>
> 4.  The principal cube root of -125 is -5.

We next consider the expression $(ð‘¥^\frac{1}{n})^n$. Note that $(ð‘¥^\frac{1}{n})^n=x$. applying the above idea, we say that $ð‘¥^\frac{1}{n}$ is is the nth root of x. in symbols, we have $ð‘¥^\frac{1}{n}=\sqrt[n]{x}$

Example:

1.  $25^\frac{1}{2}=\sqrt{25}=\sqrt{5^2}=5$ 2.$(âˆ’8)^\frac{1}{3}=\sqrt[3]{-8}=\sqrt[3]{(-2)^3}=-2$

To simplify a negative rational power, we can use the rule $x^{-n}=x^\frac{1}{n}$

> Example:
>
> 1.  $64^{-\frac{1}{3}}=\frac{1}{64^\frac{1}{3}}=\frac{1}{\sqrt[3]{(64)}}=\frac{1}{\sqrt[3]{(4^3)}}=\frac{1}{4}$
>
> 2.  $(\frac{4}{9})^{-\frac{1}{2}}=\frac{1}{(\frac{4}{9})^\frac{1}{2}}=\frac{1}{\sqrt\frac{4}{9}}=\frac{1}{\sqrt(\frac{2}{3})^2}=\frac{1}{\frac{2}{3}}=\frac{3}{2}$
>
> 3.  $(-27)^-\frac{1}{3}=\frac{1}{(-27)^\frac{1}{3}}=\frac{1}{\sqrt[3]{-27}}=\frac{1}{\sqrt[3]{(-3)^)}}=-\frac{1}{3}$

Consider a rational exponent of the form $\frac{m}{n}$ where $ð‘š â‰  1$. Since $ð‘¥^\frac{m}{n}=(ð‘¥^\frac{1}{n})^m$, we have $ð‘¥^\frac{m}{n}=(ð‘¥^\frac{1}{n})^m=(\sqrt[n]{x})^m$ or $ð‘¥^\frac{m}{n}=(ð‘¥^\frac{1}{n})^m=(x^m)^\frac{1}{n}=\sqrt[n]{x^m}$. Therefore $ð‘¥^\frac{m}{n}=(\sqrt[n]{x})^m=\sqrt[n]{x^m}$.

Observe th at the denominator of the rational exponent becomes the index of the corresponding radical expression while the numerator becomes the power of the radical expression or the power of the radicand.

In simplifying $ð‘¥^\frac{m}{n}$, we may transform it to $(\sqrt[n]{x})^m$ or $\sqrt[n]{x^m}$ The former is simpler to use than the latter since it is often not easy to see if $ð‘¥^m$ is a perfect power of *ð‘›*. For example, it is a lot easier to simplify $25^\frac{3}{2}$ as $(\sqrt{25})^3$ rather than $\sqrt{25^3}=\sqrt{15625}$ is a perfect square whose base is $125$.

> Example: Rewrite the following radicals using exponential notation:
>
> 1.  $\sqrt{3}=3^\frac{1}{2}$
>
> 2.  $\sqrt[3]{25}=\sqrt[3]{5^2}=5^\frac{2}{3}$
>
> 3.  $\sqrt[4]{x^2-2x+1}=\sqrt[4](x-1)^2=(x-1)^\frac{1}{2}$
>
> 4.  $\sqrt[3]{x^4}=x^\frac{4}{3}$
>
> 5.  $\sqrt[8]{a^7}=a^\frac{7}{8}$

> Example: Simplify the following expressions: Solution:
>
> 1.  $4^\frac{5}{2}=(2^2)^\frac{5}{2}=2^5=32$
>
> 2.  $(-32)^\frac{3}{5}=((-2)^2)^\frac{3}{5}=(-2)^3=-8$
>
> 3.  $125^{-\frac{2}{3}}=(5^3)^{-\frac{2}{3}}=(5)^{-2}=\frac{1}{5^2}=\frac{1}{25}$
>
> 4.  $-27^\frac{4}{3}=((-3)^3)^\frac{4}{3}=(-3)^4=-81$
>
> 5.  $(-32)^{-\frac{4}{5}}=((-2)^5)^{-\frac{4}{5}}=(-2)^{-4}=\frac{1}{(-2)^4}=\frac{1}{16}$

Rational exponents can also be manipulated just like any ordinary powers. This means that the rules for exponents do not change in the case of rational exponents.

> Example:
>
> 1.  $3^\frac{2}{3}.3^\frac{4}{3}=3^\frac{2}{3}+3^\frac{4}{3}=3^\frac{6}{3}=3^2=9$
>
> 2.  $\frac{x^\frac{1}{3}}{x^\frac{1}{4}}=x^{\frac{1}{3}-\frac{1}{4}}=x^\frac{1}{12}$
